### PR TITLE
updated env.template

### PR DESCRIPTION
**Pull request by richarddushime**
After updating the INSTALL.md   here  is env.template updated

### CODE REVIEW

**Review by tristanlatr — APPROVED** [review]
Looks good, thanks.

**Comment by 2ynn** [comment]
@richarddushime the `.env` file is intended to be read by `django-dotenv`, not be sourced in your shell. 
https://pypi.org/project/django-dotenv/

**Comment by tristanlatr** [comment]
> .env file is intended to be read by django-dotenv, not be sourced in your shell.

Technically both should work, but I agree this could introduce misunderstandings about setting up saskatoon, Because we would have different manner to set the environment variables.

**Comment by 2ynn** [comment]
@richarddushime I'm closing this one, feel free to reach out if the environment variables setup is still not clear.

**Pull request closed without merging**
