### PR TITLE
PR#201 Enhancements

### PR DESCRIPTION
**Pull request by farhanmasud**
Enhancements on [PR#201](https://github.com/LesFruitsDefendus/saskatoon-ng/pull/201) based on the reviews.

### CODE REVIEW

**Comment by farhanmasud** [comment]
> Have you tried loading he fixture with python saskatoon/manage.py loaddata saskatoon/fixtures/harvest-property.json ? [Ref.](https://github.com/LesFruitsDefendus/saskatoon-ng/pull/201#discussion_r845132910)

@2ynn I have tried loading the fixture and it seems to be loading the data correctly.

> If you want to regenerate it you'd need to first load it from a fresh database (on develop branch), then checkout your branch, edit the Nouveau Prorio first and last pending names from admin panel, then reexport the .json. So editing it manually for a couple changes is definitely ok. We could discuss if we really need this fixture. Note that the saskatoon/fixtures/init uses the individual, human readable .json files [Ref](https://github.com/LesFruitsDefendus/saskatoon-ng/pull/190#discussion_r845140115)

I have loaded the fixture on a fresh database and re-generated the file which I have added to this PR.

**Comment by farhanmasud** [comment]
I might need to check the `saskatoon.json` fixture in more detail. Will mark as review ready as soon as I'm done.

**Comment by farhanmasud** [comment]
@2ynn I have removed the last commit about the fixture. I think it's good to go for review of other changes that I have made. Thanks!

**Review by tristanlatr — APPROVED** [review]
Looks good, thanks.

**Comment by tristanlatr** [comment]
Hi @farhanmasud, could you update this PR to resolve conflicts?

Thanks a lot.

**Comment by farhanmasud** [comment]
@tristanlatr I have resoled the conflicts. Thanks.

**Review by 2ynn — APPROVED** [review]
great, thanks for following up on this!

**Pull request merged**
