### PR TITLE
Registration login system

### PR DESCRIPTION
**Pull request by Codde24**
I have slightly altered login system. i have enabled a user to register for an account in this system with an active status of false. The admin receives a email notification of this application and can then approve the application. When the application is approved the user receives an email notification and can then login to his account

### CODE REVIEW

**Comment by 2ynn** [comment]
thanks @Codde24  for the suggestion!
@tristanlatr does this fit with the core members workflow though? I feel like users (i.e. pickleaders) should still be created manually by admins and registration should not be made available to anyone.

**Comment by tristanlatr** [comment]
Hi @Codde24, thanks for this. it shall easy the annual registration of new pick leaders. 

I'm currently uncertain about the implementation, I'll need to look into it closer and try it out locally. 

But for sure, I think a global switch (in the admin panel) to enable/disable registration would be good. Because we would use this feature only a couple of weeks per year. 

And it does not covers the authorizations groups, an admin must edits those groups afterwards anyway, right ?
Maybe we could let the participant select how they got to this page and depending on the answer, we'd suggest pickleader or picker role. 

Talk to you later,

**Comment by 2ynn** [comment]
@tristanlatr Yeah I've already simplified the registration of new users by core members using the PersonCreateForm (which covers auth. groups assignment trough the roles checkbox list) in addition to the `reset-password` button in the Community panel. I've shown it to Simone and it seemed to be straightforward enough.

**Comment by Codde24** [comment]
> Hi @Codde24, thanks for this. it shall easy the annual registration of new pick leaders.
> 
> I'm currently uncertain about the implementation, I'll need to look into it closer and try it out locally.
> 
> But for sure, I think a global switch (in the admin panel) to enable/disable registration would be good. Because we would use this feature only a couple of weeks per year.
> 
> And it does not covers the authorizations groups, an admin must edits those groups afterwards anyway, right ? Maybe we could let the participant select how they got to this page and depending on the answer, we'd suggest pickleader or picker role.
> 
> Talk to you later,

@tristanlatr Ok sir thanks for this feedback..and yes an admin can still edit the authorization groups after

**Comment by 2ynn** [comment]
sorry @Codde24 our onboarding process has been updated using a different approach

**Pull request closed without merging**
