### PR TITLE
[#243] Remove useless chart in harvest page

### PR DESCRIPTION
**Pull request by farhanmasud**
Fixes [#243](https://github.com/LesFruitsDefendus/saskatoon-ng/issues/243) and [#242](https://github.com/LesFruitsDefendus/saskatoon-ng/issues/242)
----------
## Type of change:
- [x] Bug fix (change which fixes an issue).
- [x] New feature (change which adds functionality).
----------
## What's Changed:
- Useless chart removed from harvest detail view (from total harvested status)
- Updated link to the property record from the harvest record

--------
## Screenshots:
Screenshot from 2022-04-15 00-12-06

--------
## Affected URLs:
`127.0.0.1:8000/harvest/<int:pk>/`

-------
## Checklist:
- [x] My code follows the [style guidelines](https://github.com/LesFruitsDefendus/saskatoon-ng/blob/develop/CONTRIBUTING.md) of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.
- [ ] New and existing unit tests pass locally with my changes.

Unit tests didn't pass for this because I have used a different head `ebc6660b5c996463245472eb294161df38cc33bd` which was before the tests were fixed to avoid [#247](https://github.com/LesFruitsDefendus/saskatoon-ng/issues/247)

### CODE REVIEW

**Review by tristanlatr — APPROVED** [review]
Looks good, thanks a lot,

**Comment by farhanmasud** [comment]
@tristanlatr thanks for the approval. I'm working on [#242](https://github.com/LesFruitsDefendus/saskatoon-ng/issues/242) as well. Should I add the commit for that in this PR as well and rename this PR as Harvest page modifiactions?

**Comment by tristanlatr** [comment]
> Should I add the commit for that in this PR as well and rename this PR as Harvest page modifiactions?

Sounds good

**Comment by farhanmasud** [comment]
Apologies, didn't know renaming the branch name would close the PR. Continued at [PR #251](https://github.com/LesFruitsDefendus/saskatoon-ng/pull/251)

**Pull request closed without merging**
