### PR TITLE
Fix template errors

### PR DESCRIPTION
**Pull request by tristanlatr**
```
./saskatoon/manage.py validate_templates
```

Discovered 2 errors. 

----------
## Type of change:
- [x] Bug fix (change which fixes an issue).
----------
## What's Changed:
- fixed missing imports in the 2 templates

-------
## Checklist:
- [x] My code follows the [style guidelines](https://github.com/LesFruitsDefendus/saskatoon-ng/blob/develop/CONTRIBUTING.md) of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by tristanlatr** [comment]
Follow-up PR #169 which ensures this kind of errors won't happen again :)

**Comment by tristanlatr** [comment]
Follow-up PR #169 which ensures this kind of errors won't happen again :)

**Review by mina-andajos — APPROVED** [review]
looks great!

**Comment by tristanlatr** [comment]
@mina-andajos can you approve https://github.com/LesFruitsDefendus/saskatoon-ng/pull/250https://github.com/LesFruitsDefendus/saskatoon-ng/pull/250 also please ?

Thanks

**Comment by tristanlatr** [comment]
@mina-andajos can you approve https://github.com/LesFruitsDefendus/saskatoon-ng/pull/250https://github.com/LesFruitsDefendus/saskatoon-ng/pull/250 also please ?

Thanks

**Pull request merged**
