### PR TITLE
Rebase Develop onto Master

### PR DESCRIPTION
**Pull request by mina-andajos**
## Type of change:
- [X] Branch Rebase

---------------

### CODE REVIEW

**Comment by mina-andajos** [comment]
Hello @2ynn is this what you meant with https://github.com/LesFruitsDefendus/saskatoon-ng/pull/327#issuecomment-1166663473 ??
Or should I cherry-pick the list view speed up only?

**Review by 2ynn — DISMISSED** [review]

**Comment by 2ynn** [comment]
@mina-andajos there is a conflict left in `harvest/serializers.py`, can you look at it and test locally? thanks!

**Comment by mina-andajos** [comment]
image

hi @2ynn, it should be the other way around right? we're merging `master` into `develop` not the other way around as github says.
```py
git checkout develop
git merge master
```

**Comment by 2ynn** [comment]
@mina-andajos yes we want to rebase develop *onto* master, but merging master *into* develop works too, i changed the tittle

**Comment by 2ynn** [comment]
@mina-andajos you can you try this instead of merge: 
```
git checkout develop
git rebase master
```

**Pull request closed without merging**
