### PR TITLE
[WIP] Add a simple button / dropdown to quickly change Harvest Status

### LINKED ISSUE #199: Add a simple button / dropdown to quickly change Harvest Status
Here's what we could see at the top of a harvest page in the older saskatoon, when it's Orphan (no pick-leader associated):

Capture d’écran, le 2022-04-06 à 13 41 07

I think it would be good to improve the user experience around adroping/un-adopting a harvest and more generally speaking quickly change Harvest Status. 

A harvest could may have buttons "Adop"t/"Schedule Date"/"Mark as ready"/"Mark as succeeded" depending on the current harvest startus, instead of having to fo thought the edit form.

### PR DESCRIPTION
**Pull request by mina-andajos**
Fixes #199 
----------
## Type of change:
- [x] New feature (change which adds functionality).
----------
## What's Changed:
- one change.
- another change.
- and so on.

--------
## Screenshots:
**FOR NOW:**
1. No pickleader
image

2. With pickleader
image

--------
## Affected URLs:
e.g. `127.0.0.1:8000/harvest/<pk>`

-------
## Checklist:
- [ ] My code follows the [style guidelines](https://github.com/LesFruitsDefendus/saskatoon-ng/blob/develop/CONTRIBUTING.md) of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by mina-andajos** [comment]
Checklist:

- [ ] Finish the templates
- [ ] Add forms
- [ ] Make sure the request/response is working properly

**Comment by mina-andajos** [comment]
### Progress so far:
1- If the harvest is not orphaned: display a dropdown to change status
image

2- If it's orphaned: display a button for the picker to adopt it
image

-------------
@tristanlatr hi,
What do you think of this approach in the screenshots?
1- For the adopt button, I was thinking of making it `btn-warning/danger` to make it stand out more, what do you think?
2- For the harvest status, I'm thinking of adding just a dropdown with the current harvest status as the displayed text instead of the pen icon shown in image 1

**Comment by tristanlatr** [comment]
Hello @mina-andajos, 

The screenshots you shared are looking very good, look forward to this. 

Talk to you later,

**Comment by mina-andajos** [comment]
### So far:
I'm trying to use POST instead of GET with bootstrap dropdown, so it's taking more time to implement (using radio buttons and hiding the button with jquery).
It's still buggy (I have to press twice on the button for it to submit the form), but it kind of works from the front-end side.

### Screenshots:
image

image

--------
@tristanlatr do you believe such approach is more suitable or would you rather use GET and put anchor tags instead of radio buttons for items instead?

**Comment by mina-andajos** [comment]
Closing this PR, deleting the branch and rebasing off of master instead of develop

**Pull request closed without merging**
